### PR TITLE
BT-28: Update for Terminus 2

### PR DESCRIPTION
**Pull request by greg-1-anderson**

### CODE REVIEW

**Comment by ataylorme** [comment]
@ronan do you know if the mass update plugin is using any Terminus functionality that would be impacted by the upgrade to Terminus `2.x`?

**Comment by greg-1-anderson** [comment]
I tested this only insofar as to ensure that the "list" command works.

**Comment by ronan** [comment]
I have not had a chance to test Terminus 2 so I don't know what differences there are

**Review by ronan — APPROVED** [review]
This is fine but I have no idea if the actual plugin works. If and when it does we should update the badges on the readme as well

**Comment by greg-1-anderson** [comment]
Merging to unblock; we'll take care of anything else that pops up as follow-on work.

**Pull request merged**
